### ISSUE TITLE
hello, maybe requirements.txt is need

### ISSUE THREAD

**Issue by WangFengtu1996** [mshr-h/pico-microtvm-standalone#1]
* I can not gerenate model from onnx to c code
```
(py310) wang@legion:~/workspace/pico-microtvm-standalone$ python build_module.py -m add.onnx
Traceback (most recent call last):
  File "/home/wang/workspace/pico-microtvm-standalone/build_module.py", line 50, in <module>
    build_model_add(opts)
  File "/home/wang/workspace/pico-microtvm-standalone/build_module.py", line 21, in build_model_add
    lib = relay.build(
  File "/home/wang/anaconda3/envs/py310/lib/python3.10/site-packages/tvm/relay/build_module.py", line 351, in build
    raw_targets = Target.canon_multi_target_and_host(Target.target_or_current(target), target_host)
  File "/home/wang/anaconda3/envs/py310/lib/python3.10/site-packages/tvm/target/target.py", line 322, in canon_multi_target_and_host
    raw_targets = Target.canon_multi_target(target)
  File "/home/wang/anaconda3/envs/py310/lib/python3.10/site-packages/tvm/target/target.py", line 312, in canon_multi_target
    return convert([Target.canon_target(multi_targets)])
  File "/home/wang/anaconda3/envs/py310/lib/python3.10/site-packages/tvm/target/target.py", line 263, in canon_target
    return Target(target)
  File "/home/wang/anaconda3/envs/py310/lib/python3.10/site-packages/tvm/target/target.py", line 136, in __init__
    self.__init_handle_by_constructor__(_ffi_api.Target, target)
  File "tvm/_ffi/_cython/./object.pxi", line 132, in tvm._ffi._cy3.core.ObjectBase.__init_handle_by_constructor__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 287, in tvm._ffi._cy3.core.ConstructorCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 262, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 251, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
ValueError: Traceback (most recent call last):
  2: TVMFuncCall
  1: tvm::TargetInternal::ConstructorDispatcher(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::Target::Target(tvm::runtime::String const&) [clone .cold]
  File "/workspace/tvm/src/target/target.cc", line 580
ValueError: Error when parsing target["runtime"]: Cannot recognize 'runtime'. Candidates are: constants-byte-alignment, from_device, march, host, mcpu, libs, model, device, workspace-byte-alignment, target_device_type, tag, keys. Target creation from string failed: c --runtime=c --system-lib --link-params
```
* tvm version
```
apache-tvm                0.11.1
```

**Comment by mshr-h** [comment]
Seems like you're using the wrong tvm version.
I don't remember which tvm version was used, but according to the below include header, it was tvm 0.8.
https://github.com/mshr-h/pico-microtvm-standalone/blob/c59fd0df176fc77558026cd9c5b044c1fa8753eb/src/tvm/standalone_crt/include/tvm/runtime/c_runtime_api.h#L69C22-L69C30

**Comment by mshr-h** [comment]
@WangFengtu1996 
I updated the README and code to support TVM v0.17.
Build works fine but haven't tested the binary on the actual hardware.

**Comment by WangFengtu1996** [comment]
thks, i will try it.
